import { MenuItem, Transaction } from "@/types";

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: "menu-1",
    name: "Nasi Goreng Nyamleng",
    category: "Makanan",
    price: 18000,
    hpp: 10000,
    taxPercent: 10,
    icon: "🍳",
    isActive: true,
  },
  {
    id: "menu-2",
    name: "Mie Goreng Jawa",
    category: "Makanan",
    price: 16000,
    hpp: 9000,
    taxPercent: 10,
    icon: "🍜",
    isActive: true,
  },
  {
    id: "menu-3",
    name: "Ayam Geprek Sambal Korek",
    category: "Makanan",
    price: 20000,
    hpp: 12000,
    taxPercent: 10,
    icon: "🍗",
    isActive: true,
  },
  {
    id: "menu-4",
    name: "Es Teh Manis Jumbo",
    category: "Minuman",
    price: 5000,
    hpp: 2000,
    taxPercent: 10,
    icon: "🍹",
    isActive: true,
  },
  {
    id: "menu-5",
    name: "Es Jeruk Peras",
    category: "Minuman",
    price: 7000,
    hpp: 3000,
    taxPercent: 10,
    icon: "🍊",
    isActive: true,
  },
  {
    id: "menu-6",
    name: "Kopi Tubruk Malang",
    category: "Minuman",
    price: 8000,
    hpp: 3500,
    taxPercent: 10,
    icon: "☕",
    isActive: true,
  },
  {
    id: "menu-7",
    name: "Tahu Crispy Sambal Kecap",
    category: "Cemilan",
    price: 10000,
    hpp: 4000,
    taxPercent: 10,
    icon: "🍢",
    isActive: true,
  },
  {
    id: "menu-8",
    name: "Pisang Goreng Keju",
    category: "Cemilan",
    price: 12000,
    hpp: 5000,
    taxPercent: 10,
    icon: "🍌",
    isActive: true,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "trx-001",
    orderNumber: "#001",
    customerName: "Budi",
    orderType: "dine-in",
    tableNumber: "04",
    subtotal: 34000,
    discountType: "fixed",
    discountValue: 4000,
    discountAmount: 4000,
    tax: 3000,
    total: 33000,
    hppTotal: 19000,
    netProfit: 14000,
    cashReceived: 50000,
    change: 17000,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    items: [
      {
        id: "ti-1",
        nameSnapshot: "Nasi Goreng Nyamleng",
        priceSnapshot: 18000,
        hppSnapshot: 10000,
        qty: 1,
      },
      {
        id: "ti-2",
        nameSnapshot: "Mie Goreng Jawa",
        priceSnapshot: 16000,
        hppSnapshot: 9000,
        qty: 1,
      },
    ],
  },
  {
    id: "trx-002",
    orderNumber: "#002",
    customerName: "Siti",
    orderType: "takeaway",
    tableNumber: "-",
    subtotal: 25000,
    discountType: null,
    discountValue: 0,
    discountAmount: 0,
    tax: 2500,
    total: 27500,
    hppTotal: 14000,
    netProfit: 13500,
    cashReceived: 30000,
    change: 2500,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    items: [
      {
        id: "ti-3",
        nameSnapshot: "Ayam Geprek Sambal Korek",
        priceSnapshot: 20000,
        hppSnapshot: 12000,
        qty: 1,
      },
      {
        id: "ti-4",
        nameSnapshot: "Es Teh Manis Jumbo",
        priceSnapshot: 5000,
        hppSnapshot: 2000,
        qty: 1,
      },
    ],
  },
];
